- name: Docker, Node, Npm installation
  hosts: vps
  become: yes

  tasks:
  - name: Update apt
    ansible.builtin.apt:
      update_cache: yes

  - name: Install required packages
    ansible.builtin.apt:
      name: 
        - docker.io
        - docker-compose
        - nodejs
        - npm
      state: present

      cd ~
          if [ ! -d "ansible/.git" ]; then
              git clone git@github.com:MariuszBlaszczyk/Automations.git
          else
              echo "Repozytorium istnieje, wykonuje git pull"
              cd ansible
              git pull origin main
              cd ..
          fi